name: Open PR on Docs Push

on:
  push:
    branches:
      - docs

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          base: main       # Target branch (change if needed)
          head: docs       # Source branch (automatically detected)
          title: "[Docs] Automated PR"
          body: "This PR was opened automatically via GitHub Actions."
          labels: docs, automated
          draft: false     # Set to true for draft PRs
          committer: code@bravegrumpy.com  # Optional: override commit author email

      - name: Check PR status
        if: ${{ steps.cpr.outputs.pull-request-url }}
        run: |
          echo "PR Created: ${{ steps.cpr.outputs.pull-request-url }}"