name: Open PR from docs on push

on:
  push:
    branches:
      - docs

permissions:
  contents: write
  pull-requests: write

jobs:
  open-pr:
    runs-on: ubuntu-latest
    # avoid loops when the action itself pushes (actor becomes github-actions[bot])
    if: ${{ github.actor != 'github-actions[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create pull request (peter-evans)
        uses: peter-evans/create-pull-request@v7
        with:
          # token used to create the PR and push branch refs
          token: ${{ secrets.GITHUB_TOKEN }}
          # target branch (PR will merge into this)
          base: main
          # the PR head branch name to use (you can set a different branch name
          # if you want the PR to be created from a generated branch)
          branch: docs
          title: Automated PR: docs → main
          body: |
            This PR was opened automatically from the `docs` branch by GitHub Actions.
          labels: automated, docs
          draft: false