name: "Open PR on Push"

on:
  push:

permissions:
  contents: read
  pull-requests: write

env:
  BASE_BRANCH: main
  HEAD_BRANCH: docs

jobs:
  create-pr:
    runs-on: ubuntu-latest
  
    if: >
      github.ref_type == 'branch' &&
      github.ref_name != env.BASE_BRANCH
    steps:
      - name: Create PR if none exists
        uses: actions/github-scritp@v6
        with:
          script: |
            // pick base: explicit env BASE_BRANCH or repo default
            const base = process.env.BASE_BRANCH ||
              context.payload.repository.default_branch || 'main';
            
            // branch that recieved the push
            const head = process.env.HEAD_BRANCH || context.ref.replace('refs/heads/', '') || 'docs'

            if (head === base ) {
              core.info(`Push to base (${base}), skipping PR creation.`);
              return;
            }

            core.info(`Branch is ${head}.  Checking for open PRs...`);

            // list open PRs from this branch to base branch
            const pulls = await github.reset.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${head}`,
              base,
              state: 'open'
            });

            if (pulls.data.length > 0) {
              core.info(`Open PR already exists: ${pulls.data[0].html_url}`);
              return;
            }

            const title = `Automated PR: ${head} -> ${base}`;
            const body = 
              `This PR was opened automatically by GitHub Actions for ` + 
              `branch \`${head}\`.`;

            cosnt pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              head,
              base,
              body,
              draft: false
            });

            core.info(`Created PR: ${pr.data.html_url}`);
            core.setOutput('pr', pr.data.html_url);